AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Spring Boot 4 AWS Lambda example

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/spring-lambda.jar
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker
      Runtime: java17
      MemorySize: 512
      Timeout: 10
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: hello
      Events:
        Hello:
          Type: HttpApi
          Properties:
            Path: /hello
            Method: GET